### ISSUE TITLE
about FPS

### ISSUE THREAD

**Issue by nhw649** [xushilin1/RAP-SAM#4]
Why is there such a big difference between the FPS I tested and the real-time FPS? Did I do something wrong? I'm directly using the configuration file you provided, without any modifications. The FPS is obtained on one 3090 card.
Run command: ```./tools/dist_test.sh configs/rap_sam/eval_rap_sam_coco.py $CKPT ./rapsam_r50_12e.pth $NUM_GPUS 1```

![QQ截图20240317004021](https://github.com/xushilin1/RAP-SAM/assets/67191596/faba1727-8c99-4854-a0d5-04aa6d880675)

**Comment by Masrur02** [comment]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1345001) of binary: /home/soicroot/miniconda3/envs/rap/bin/python
Traceback (most recent call last):
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/soicroot/miniconda3/envs/rap/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-18_15:39:59
  host      : soicroot
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1345001)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
``

I get this error after running this
**./tools/dist_test.sh configs/rap_sam/eval_rap_sam_coco.py $CKPT ./rapsam_r50_12e.pth $NUM_GPUS 1**

**Comment by xushilin1** [comment]
Thanks for your interest in our work.  

Data processing for interactive segmentation is time-consuming. You can evaluate the model's speed by testing it with COCO panoptic segmentation.

**Comment by nhw649** [comment]
> Thanks for your interest in our work.
> 
> Data processing for interactive segmentation is time-consuming. You can evaluate the model's speed by testing it with COCO panoptic segmentation.


Which configuration file should I run?

**Comment by lxtGH** [comment]
@xushilin1 @HarborYuan Please provide the test scripts for FPS.

**Comment by HarborYuan** [comment]
Hi @nhw649 ,

Thanks for your interest in our work.

The FPS of the models in our paper follows the common practice that does not involve the data pre-processing time since it will vary significantly on different machines. You can use the [script](https://github.com/open-mmlab/mmdetection/blob/main/tools/analysis_tools/benchmark.py) to test the FPS. Our code is fully compatible with mmdet. Thus, you can directly specify config for benchmarking.

Please note that different GPUs may lead to very different results.

Please let me know if you have any other questions.
